CFLAGS = -Wall -O2
LDFLAGS = -lm -pthread -lSDL2 -lpng

CFLAGS += $(shell pkg-config --cflags sdl2)
LDFLAGS += $(shell pkg-config --libs sdl2)

splitsdl : splitsdl.c library.c libgfx.c
	cc splitsdl.c -DOS_MACOS -o splitsdl $(LDFLAGS) $(CFLAGS) -w
